#! /usr/bin/env perl

use strict;
use warnings;

use Getopt::Long qw(:config posix_default no_ignore_case gnu_compat);
use Pod::Usage;

GetOptions(
    'v|verbose'   => \my $is_verbose,
    'h|help'      => sub { pod2usage(1) },
    'm|man'       => sub { pod2usage(-verbose => 2) },
) or pod2usage(1);

main: {
    my ( $target_commit_hash ) = @ARGV;

    my @merged_commit_hash_list = split "\n", `git log --merges --pretty=%H`;
    if ( grep { $_ eq $target_commit_hash } @merged_commit_hash_list ) {
        print "this commit hash is MERGE COMMIT: $target_commit_hash\n";
        exit 1;
    }

    for my $commit_hash (@merged_commit_hash_list) {
        my $is_found = system( "git log HEAD...$commit_hash --pretty=%H | grep $target_commit_hash") ? 0 : 1;

        next unless $is_found;

        print "=== FOUND ===\n";

        my $option = $is_verbose ? '-m' : '';
        print `git show $option $commit_hash`;

        exit;
    }

    print "=== NOT FOUND ===\n";
    exit 2;
}


__END__

=head1 NAME

xxxxxxx.pl - Do something

=head1 SYNOPSIS

  $ xxxxxxx.pl args

=head1 OPTIONS

  --help,    -h      show this message
  --man,     -m      full documentaion
